/*
 * supercap_def.h
 *
 *  Created on: Jul 5, 2024
 *      Author: YassineBakkali
 */

#ifndef STM_UTILS_INC_SUPERCAP_DEF_H_
#define STM_UTILS_INC_SUPERCAP_DEF_H_

//#define BOARD_ID 0x01
//#define CALIBRATION_MODE true

#ifndef BOARD_ID
#error "BOARD_ID VARIABLE MUST BE DEFINED."
#endif

#ifndef CALIBRATION_MODE
#error "CALIBRATION MODE VARIABLE MUST BE DEFINED."
#endif

#define P_BATTERY_KP 3.85f
#define P_BATTERY_KI 0.048f
#define P_BATTERY_KD 0.001f

#define P_BATTERY_MIN_OUTPUT -400.0f

#define P_CHASSIS_MAX_OUTPUT 2.0f
#define P_CHASSIS_MIN_OUTPUT -2.0f

#define I_SUPERCAP_KP 0.0207f
#define I_SUPERCAP_KI 0.00022f
#define I_SUPERCAP_KD 0.0f

#define I_SUPERCAP_INTEG_MAX 1.621f
#define I_SUPERCAP_INTEG_MIN 0.127f
#define I_SUPERCAP_MAX_OUTPUT 1.621f
#define I_SUPERCAP_MIN_OUTPUT 0.127f

#define I_SUPERCAP_INIT_VAL 0.14f

#define V_SUPERCAPMAX_KP 0.001f
#define V_SUPERCAPMAX_KI 0.0025f
#define V_SUPERCAPMAX_KD 0.001f

#define V_SUPERCAPMAX_INTEG_MAX 1.6f
#define V_SUPERCAPMAX_INTEG_MIN 1.005f
#define V_SUPERCAPMAX_MAX_OUTPUT 1.6f
#define V_SUPERCAPMAX_MIN_OUTPUT 1.005f

#define V_SUPERCAPMAX_REF 26.0f

#define V_SUPERCAPMAX_INIT_VAL 1.4f

#define V_SUPERCAPMIN_KP 0.001f
#define V_SUPERCAPMIN_KI 0.0025f
#define V_SUPERCAPMIN_KD 0.0f

#define V_SUPERCAPMIN_INTEG_MAX 0.179f
#define V_SUPERCAPMIN_INTEG_MIN 0.127f
#define V_SUPERCAPMIN_MAX_OUTPUT 0.179f
#define V_SUPERCAPMIN_MIN_OUTPUT 0.127f

#define V_SUPERCAPMIN_REF 2.7f

#define V_SUPERCAPMIN_INIT_VAL 0.1f

#define SUPERCAP_CURRENT_MAX 18.0f
#define SUPERCAP_CURRENT_MIN -18.0f

#define SUPERCAP_CURRENT_SAFETY_MAX 20.5f

#define ESR_VALUE 0.17f // TODO : MEASURE ACTUAL ESR VALUE. Someday. probably never.

#define SUPERCAP_MAX_VOLTAGE 25.5f //
#define SUPERCAP_MIN_VOLTAGE 3.00f //

#define MIN_PMM_VOLTAGE 18.0f // (24V-4V)
#define MAX_PMM_VOLTAGE 28.0f // (24V+4V)

#define MAX_CAP_CURRENT 18.0f

#define TEMP_PARAM_B 3380.0f
#define TEMP_FIX_RES 10000.0f
#define TEMP_NTC_RES 10000.0f
#define TEMP_CELSIUS_CONST 273.15f
#define TEMP_AMBIANT 298.15f

#define MIN_BAT_VOLTAGE 20.97f

#endif /* STM_UTILS_INC_SUPERCAP_DEF_H_ */
