/*
 * supercap_def.h
 *
 *  Created on: Jul 5, 2024
 *      Author: YassineBakkali
 */

#ifndef STM_UTILS_INC_SUPERCAP_DEF_H_
#define STM_UTILS_INC_SUPERCAP_DEF_H_

#define P_BATTERY_KP 0.05f
#define P_BATTERY_KI 0.008f
#define P_BATTERY_KD 0.0f

#define P_BATTERY_MIN_OUTPUT -205.0f

#define P_CHASSIS_KP 0.00f
#define P_CHASSIS_KI 0.00f
#define P_CHASSIS_KD 0.0f

#define P_CHASSIS_MAX_OUTPUT 2.0f
#define P_CHASSIS_MIN_OUTPUT -2.0f

#define I_SUPERCAP_KP 0.0007f
#define I_SUPERCAP_KI 0.00062f
#define I_SUPERCAP_KD 0.0f

#define I_SUPERCAP_MAX_OUTPUT 1.4f
#define I_SUPERCAP_MIN_OUTPUT 0.1f

#define I_SUPERCAP_INIT_VAL 0.14f

#define V_SUPERCAPMAX_KP 0.001f
#define V_SUPERCAPMAX_KI 0.0025f
#define V_SUPERCAPMAX_KD 0.0f

#define V_SUPERCAPMAX_MAX_OUTPUT 1.4f
#define V_SUPERCAPMAX_MIN_OUTPUT 0.1f

#define V_SUPERCAPMAX_REF 26.0f

#define V_SUPERCAPMAX_INIT_VAL 1.4f

#define V_SUPERCAPMIN_KP 0.001f
#define V_SUPERCAPMIN_KI 0.0025f
#define V_SUPERCAPMIN_KD 0.0f

#define V_SUPERCAPMIN_MAX_OUTPUT 1.4f
#define V_SUPERCAPMIN_MIN_OUTPUT 0.1f

#define V_SUPERCAPMIN_REF 2.7f

#define V_SUPERCAPMIN_INIT_VAL 0.1f

#define SUPERCAP_CURRENT_MAX 10.0f
#define SUPERCAP_CURRENT_MIN -10.0f

#define SUPERCAP_CURRENT_SAFETY_MAX 12.5f

#define ESR_VALUE 0.12f // MEASURE ACTUAL ESR VALUE

#define SUPERCAP_MAX_VOLTAGE 24.0f // ~(0.85*27V) TO BE CHANGED IF WE DO NOT USE THE SAME BANK
#define SUPERCAP_MIN_VOLTAGE 2.97f // (0.11*27V) SAME THING

#define MIN_PMM_VOLTAGE 18.0f // (24V-4V)
#define MAX_PMM_VOLTAGE 28.0f // (24V+4V)

#define MAX_CAP_CURRENT 10.0f
// INDUCTANCE'S RATED CURRENT IS 15A. MAX CURRENT SHOULD BE A BIT LESS THAN 15A.
// AVALON HAS A 2OZ THICK SURFACE LAYERS. SHOULD BE ABLE TO HANDLE ALL THE CURRENT.
// TEST HEAT DISTRIBUTION BEFORE DEPLOYMENT. DO NOT TWEAK THE CODE AT THE LAST MOMENT
// BEFORE COMPETITION IF YOU DO NOT KNOW HOW IT WORKS.

#define TEMP_PARAM_B 3380.0f
#define TEMP_FIX_RES 10000.0f
#define TEMP_NTC_RES 10000.0f
#define TEMP_CELSIUS_CONST 273.15f
#define TEMP_AMBIANT 298.15f

#endif /* STM_UTILS_INC_SUPERCAP_DEF_H_ */
